[package]
name    = "frequency-phaser"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "frequency-phaser"
path = "src/main.rs"

[dependencies]
fp-core   = { path = "../core" }
cpal      = "0.15"
ratatui   = "0.29"
crossterm = { version = "0.28", features = [] }
anyhow    = "1"
symphonia  = { version = "0.5", default-features = false, features = [
    "mp3", "wav", "pcm", "adpcm",
] }
serialport = "4"
